# All Thresholds, Weights, Penalties and Boost factors
COLUMN_DESC_THRESHOLD = 0.65
COLUMN_WEIGHTED_SCORE_THRESHOLD = 0.7
COLUMN_LINEAGE_THRESHOLD = 0.7
TABLE_SIMILARITY_THRESHOLD = 0.7
TABLE_DESC_THRESHOLD = 0.65
TABLE_WEIGHTED_SCORE_THRESHOLD = 0.7

SCHEMA_COL_PAIR_SCORE_THRESHOLD = 0.7
SCHEMA_COL_NAME_WEIGHT = 0.8
SCHEMA_COL_DTYPE_WEIGHT = 0.2

OVERALL_NAME_SCORE_WEIGHT = 0.3
OVERALL_PLATFORM_SCORE_WEIGHT = 0.1
OVERALL_SCHEMA_SCORE_WEIGHT = 0.6
OVERALL_DESC_BOOST = 1.2
OVERALL_DESC_PENALTY = 0.9
OVERALL_DESC_SCORE_THRESHOLD = 0.5
OVERALL_TABLE_SIMILARITY_THRESHOLD = 0.6

COLUMN_DTYPE_BOOST = 1.2
COLUMN_DTYPE_PENALTY = 0.95
COLUMN_DESC_BOOST = 1.2
COLUMN_DESC_PENALTY = 0.9
COLUMN_TABLE_SIMILARITY_BOOST = 1.2
COLUMN_LINEAGE_BOOST = 1.2
