infotypes_to_use = [
    "Street_Address",
    "Gender",
    "Credit_Debit_Card_Number",
    "Email_Address",
    "Phone_Number",
    "Full_Name",
    "Age",
    "IBAN",
    "Vehicle_Identification_Number",
    "US_Social_Security_Number",
    "IP_Address_v4",
    "IP_Address_v6",
    "Swift_Code",
    "US_Driving_License_Number",
]
